### ISSUE TITLE
how to run it

### ISSUE THREAD

**Issue by archenemies** [jaebradley/flights-search-cli#30]
Can we update the README to say how I should run the program after having cloned the source tree? It says something about `npm install` but I imagine this is not using the source I downloaded. Thanks!

**Comment by jaebradley** [comment]
@archenemies I think the following is in the README right now

![image](https://user-images.githubusercontent.com/8136030/63872179-38ecab80-c972-11e9-8897-8da5dccde58c.png)

But I can definitely make the implication of the command more explicit!

**Comment by archenemies** [comment]
Thank you for the reply! I'm not sure if what I said was understood so I'm pasting it again:

> Can we update the README to say how I should run the program after having cloned the source tree? It says something about npm install but I imagine this is not using the source I downloaded. Thanks!

Does "npm install" use the "source I downloaded" when I "cloned the source tree"? (yes or no)

e.g.

    git clone https://github.com/jaebradley/flights-search-cli
    npm install flights-search-cli --global

Is the second command using the results of the first command? Or is it downloading a package named "flights-search-cli" from some other package repository?

What if I do

    git clone https://github.com/jaebradley/flights-search-cli
    # edit flights-search-cli/src/executables/flights.js
    npm install flights-search-cli --global

will my changes to the source code be visible to me when I run "flights search"?

If "yes" then I think the README should include the `git clone` command before the `npm install` command. If "no" then the purpose of submitting this issue was to ask how I should accomplish running the code that I downloaded (and possibly modified), rather than the code in a package repository.

Thank you. I apologize for not being familiar with `npm`.

**Comment by jaebradley** [comment]
@archenemies oh I see now! You want some suggestions for local execution (i.e. I clone the repo, make changes locally, and build and test these changes)?

Sorry, I quickly read through the initial issue comment - I can definitely add a guide for local development / execution.

Thanks for following up and apologies for the miscommunication on my end!

**Comment by archenemies** [comment]
Thank you!
